' ============================================================
'  OpenClaw Gateway ??Silent Hidden Launcher
'  Called by the "OpenClaw Gateway" scheduled task at boot.
'  Runs gateway.cmd with ZERO window visibility (windowStyle=0).
'
'  This VBScript wrapper is essential because:
'    1. schtasks /CREATE cannot set "Hidden" window style directly.
'    2. Even with task settings set to "Hidden", CMD windows can flash.
'    3. WScript.Shell.Run with windowStyle=0 guarantees NO window at all.
'
'  Generated by: OpenClaw Silent Boot Guardian (Antigravity Agent)
'  Date: 2026-06-21
' ============================================================
Dim shell
Set shell = CreateObject("WScript.Shell")

' Set environment so the child process inherits system env vars
' (Task Scheduler in SYSTEM context loads Machine-level env vars automatically)

' Run gateway.cmd completely hidden (windowStyle=0), do NOT wait for exit (False)
shell.Run """C:\\Users\\10979\\.openclaw\\gateway.cmd""", 0, True

Set shell = Nothing
